//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        public int id { get; set; }
        public string title { get; set; }
        public int author_id { get; set; }
    
        public virtual authors authors { get; set; }
    }
}
